name:                scratch-compiler
version:             0.1.0.0
github:              "Johan-Mi/scratch-compiler"
license:             WTFPL
author:              "Johan Milanov"
maintainer:          "johanmi@protonmail.com"
copyright:           "2021 Johan Milanov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Johan-Mi/scratch-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- text
- hspec

library:
  source-dirs: src

executables:
  scratch-compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scratch-compiler

tests:
  scratch-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scratch-compiler
